version: 2
jobs:
  build_environment:
    machine: true
    working_directory: ~/AI_hackathon
    steps:
      - checkout
      - run:
          name: Build tensorflow docker image
          command: docker build -f runtime/Dockerfile .

  generate-website:
    working_directory: ~/ngraph-ci-test
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: Install requirements
          command: sudo pip install --upgrade -r requirements_web.txt
      - run:
          name: Generate static page
          command: python3 website-generator/generator.py


      - add_ssh_keys:
          fingerprints:
            - "75:5b:30:a6:df:e6:25:9c:80:5f:30:6a:98:a1:e4:39"

      - run:
          name: Deploy results
          working_directory: ~/ngraph-ci-test
          command: |
            git config --global user.email "blue@wolves.com"
            git config --global user.name "blue-wolves"

            git pull origin master
            git add docs
            git commit --allow-empty -m "Test update [ci skip]"
            git push origin master


workflows:
  version: 2
  build_on_commit:
    jobs:
      - build_environment
      - generate-website

  daily_workflow:
    jobs:
      - build_environment
      - generate-website

    triggers:
      - schedule:
          cron: "00 11 * * *"
          filters:
            branches:
              only:
                - master
